export const Productos = [
  (printers = {
    id: 1,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "Part numbers: W1B31C",
    descripcion: "PRINTER HP PAGEWIDE PRO MFP 772DW''",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 2,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 3,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 4,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 5,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 6,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 7,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 8,
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 9,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  },
  {
    id: 10,
    categoria: "Printer",
    img: "https://github.com/FabricioGodoy/imagenes/blob/main/productos/Printer.jpg?raw=true",
    codigo: "impresora",
    descripcion: "impresora",
    marca: "TNT",
    caracteristicas: [" imprime "],
  }),
  (accessPoint = {
    id: 1,
    categoria: "accessPoint",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/AccessPoints_large.webp",
    codigo: "access Point",
    descripcion: "access Point",
    marca: "TNT",
    caracteristicas: [" access Point "],
  },
  {
    id: 2,
    categoria: "accessPoint",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/AccessPoints_large.webp",
    codigo: "access Point",
    descripcion: "access Point",
    marca: "TNT",
    caracteristicas: [" access Point "],
  }),
  (switches = {
    id: 1,
    categoria: "switches",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/Switches_large.webp",
    codigo: "switches",
    descripcion: "switches",
    marca: "TNT",
    caracteristicas: [" switches "],
  },
  {
    id: 1,
    categoria: "switches",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/Switches_large.webp",
    codigo: "switches",
    descripcion: "switches",
    marca: "TNT",
    caracteristicas: [" switches "],
  }),
  (telephones = {
    id: 1,
    categoria: "telephones",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/Telephones_large.webp",
    codigo: "telephones",
    descripcion: "telephones",
    marca: "TNT",
    caracteristicas: [" telephones "],
  },
  {
    id: 2,
    categoria: "telephones",
    img: "https://raw.githubusercontent.com/FabricioGodoy/imagenes/main/productos/Telephones_large.webp",
    codigo: "telephones",
    descripcion: "telephones",
    marca: "TNT",
    caracteristicas: [" telephones "],
  }),
];
